### ISSUE TITLE
Add quickfort utility

### ISSUE THREAD

**Issue by loredev10** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#48]
Is it possible to add quickfort utility to this LNP?

**Comment by carterscottm** [comment]
It's already sort of included.  QuickFort is windows only last time I checked.  Instead, I've included qfconvert in ./LNP/utilitities. Since it's a command line only application, it's not shown on the utilities screen of PyLNP.

See ./LNP/about/QFconvert.md for instructions on using the utility.  I've not used QuickFort or qfconvert myself, but included it for those that do.
